translation:
    locales: ["en", "ru"]
    edit_in_place:
        enabled: false
        config_name: app
    configs:
        app:
            dirs: ["%kernel.project_dir%/templates", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            new_message_format: ""
    webui:
        enabled: true
        allow_create: false
        allow_delete: false

when@dev:
    translation:
        symfony_profiler:
            enabled: false
