version: "3.4"

# Development environment override
services:
  php:
    container_name: php
    build:
      target: app_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  worker:
    container_name: worker
    build:
      target: app_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    entrypoint: php bin/console messenger:consume async -vv

  caddy:
    container_name: caddy
    command:
      [
        "caddy",
        "run",
        "--config",
        "/etc/caddy/Caddyfile",
        "--adapter",
        "caddyfile",
        "--watch",
      ]
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  node:
    container_name: node
    build:
      context: .
      target: app_node
    command: 'sh -c "npm install; npm run dev-server -- --server-type https --host 0.0.0.0 --public localhost:8080"'
    environment:
      NODE_END: "${NODE_ENV:-development}"
    volumes:
      - ./:/srv/app
    ports:
      - "127.0.0.1:8080:8080"

  rabbitmq:
    ports:
      - "127.0.0.1:5672:5672" # dsn server
      - "127.0.0.1:15672:15672" # web ui

  ###> symfony/mercure-bundle ###
  ###< symfony/mercure-bundle ###

  ###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    ports:
      - "127.0.0.1:5432:5432"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports:
      - "127.0.0.1:1025:1025" # dsn server
      - "127.0.0.1:1080:1080" # web ui
###< symfony/mailer ###
